apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:  # We dont need to worry about converting to base64
  POSTGRES_USER: vishu
  POSTGRES_PASSWORD: password
  POSTGRES_DB: stackpgdb
  
  DB_HOST: stacklifo-postgres
  DB_DRIVER: postgres
  DB_USER: vishu
  DB_PASSWORD: password
  DB_NAME: stackpgdb
  DB_PORT: 5432 