apiVersion: v1                                      # API version
kind: Service                                       # Type of kubernetes resource 
metadata:
  name: stacklifo-mysql                          # Name of the resource
  labels:                                           # Labels that will be applied to the resource
    app: stacklifo-mysql
spec:
  type: NodePort
  ports:
    - port: 3306
  selector:                                         # Selects any Pod with labels `app=stacklifo-mysql,tier=postgres`
    app: stacklifo-mysql
    tier: mysql