#FYI --- it is not advisable to push secrets into public repo.. but I'm using it for demonstartion purpose
# Actually its a mini-proj that needs to be submitted
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
stringData:  # We dont need to worry about converting to base64
  MYSQL_ROOT_USER: root
  MYSQL_ROOT_PASSWORD: 4b3
  MYSQL_DATABASE: stackdb
  #MYSQL_ROOT_PASSWORD: 4b3
  
  DB_HOST: stacklifo-mysql
  DB_DRIVER: mysql
  DB_USER: root
  DB_PASSWORD: 4b3
  DB_NAME: stackdb
  DB_PORT: "3306" 